
Keep it simple and to the basics unless it's necessary.

* Help

C-h k describe-key
C-h c describe-key-briefly
C-h f describe-function
C-h v describe-variable
C-h o describe-symbol
C-h P describe-package
C-h m describe-mode

* Undo

C-/
C-x u
C-_   undo

* Canceling

C-g
ESC ESC ESC keyboard-quit

* Navigation

C-f forward-char
C-b backward-char
C-n next-line
C-p previous-line

C-a move-beginning-of-line
C-e move-end-of-line

M-f forward-word
M-b backward-word

M-< beginning-of-buffer
M-> end-of-buffer

C-v scroll-up-command
M-v scroll-down-command

M-g M-g goto-line

** Ring navigation

C-SPC C-SPC (push to mark ring)
C-u C-SPC (return to last mark)
C-x C-SPC pop-global-mark

* Erasing Text

BACKSPACE delete-backward-char
C-d delete-char
C-k kill-line

M-BACKSPACE backward-kill-word
M-d kill-word

* Blank lines and whitespace

C-o open-line
C-x C-o delete-blank-lines

* Region (selection)

C-SPC set-mark-command
C-x C-x exchange-mark-and-point

M-h mark-paragraph
C-M-h mark-defun
C-x h mark-whole-buffer

C-w kill-region
M-w kill-ring-save

* Files

C-x C-f find-file
C-x C-s save-buffer

* Inside minibuffer

M-p previous-history-element
M-n next-history-element

* Repetition and keyboard macro

C-u <n> [<n>...] <command>
C-x z [z...] repeat

* Word count

M-= count-words-region
M-x count-words


* TODO

A better way to scroll/find/go to a location outside the
window. Scrolling is only useful when I want to skim/scan a file top
to bottom, otherwise it is very distracting and tiring.

Push and pop location in a unified way. Return from xref definition,
return from previous mark, etc.

Better navigation between help buffers, forward and backward. It's not
desired that a second help buffer opens in the other window.

Goto help at point, like 'M-.'. And return, like 'M-,'. Bind
helpful-at-point.

Check help-* and helpful-* functions. help and helpful mode commands
in manual.

Run C-h m in Help and Helpful mode and check mode specific key
bindings.

Separate "selection" and "adding a location to mark ring". I don't
want the mark to be saved every time text is selected.

Stop Ivy matching when necessary. For example, there is an existing
file design-top.v, typing C-x C-f top.v ENTER opens design-top.v
rather than creating top.v.
