#+TITLE: Emacs Cheat Sheet
#+AUTHOR: Can Aknesil
#+STARTUP: content
#+OPTIONS: toc:nil

Keep it simple and to the basics unless it's necessary.

* When in trouble
** Help

C-h k describe-key
C-h c describe-key-briefly
C-h f describe-function
C-h v describe-variable
C-h o describe-symbol
C-h P describe-package
C-h m describe-mode

** Undo

C-/
C-x u
C-_   undo

C-? undo-redo

** Canceling

C-g
ESC ESC ESC keyboard-quit


* Navigation
** Basic navigation

C-f forward-char
C-b backward-char
C-n next-line
C-p previous-line

C-a move-beginning-of-line
C-e move-end-of-line

M-f forward-word
M-b backward-word

M-< beginning-of-buffer
M-> end-of-buffer

C-v scroll-up-command
M-v scroll-down-command

C-l recenter-top-bottom
C-M-l reposition-window

M-g M-g goto-line

** Search

C-s isearch-forward
C-r isearch-backward
C-s C-s (repeat previous search)
C-r C-r (repeat previous search)

M-s w isearch-forward-word
M-s _ isearch-forward-symbol
M-s . isearch-forward-symbol-at-point

C-M-s isearch-forward-regexp
C-M-r isearch-backward-regexp

M-r isearch-toggle-regexp (within isearch)

M-s o occur

** Ring navigation

C-SPC C-SPC (push to mark ring)
C-u C-SPC (return to last mark)
C-x C-SPC pop-global-mark

** Follow mode

M-x follow-mode

** Narrowing

See the manual.

** View Mode

See the manual.


* Basic editing
** Deletion, killing, and yanking

BACKSPACE delete-backward-char
C-d delete-char

C-k kill-line
C-SHIFT-BACKSPACE kill-whole-line

M-BACKSPACE backward-kill-word
M-d kill-word

C-M-k kill-sexp

C-w kill-region
M-w kill-ring-save

C-y yank
M-y yank-pop
C-u C-y (yank and leave point at the beginning)
C-u M-y (yank-pop and leave point at the beginning)

** Region (selection)

C-SPC set-mark-command
C-x C-x exchange-mark-and-point

M-h mark-paragraph
C-M-h mark-defun
C-x h mark-whole-buffer


* Smart editing
** Blank lines and whitespace

C-o open-line

M-\ delete-horizontal-space
M-SPC just-one-space
C-x C-o delete-blank-lines
M-^ delete-indentation

** Replacement

M-x replace-string
M-% query-replace

M-x replace-regexp
C-M-% query-replace-regexp

** Smart insertion

C-x r N rectangle-number-lines
C-u C-x r N (rectangle-number-lines custom initial number and format string)

** Repetition, and keyboard macro

C-u <n> [<n>...] <command>
C-x z [z...] repeat

C-x ( kmacro-start-macro
C-x ) kmacro-end-macro
C-x e [e...] kmacro-end-and-call-macro

** Rectangles

C-x r t string-rectangle

C-x r k kill-rectangle
C-x r c clear-rectangle

C-x r M-w copy-rectangle-as-kill
C-x r y yank-rectangle

** Correcting spelling

M-$ ispell-word
M-x ispell
M-x ispell-comments-and-strings

** Transposing text

See the manual.

** Case conversion

See the manual.

** Registers

See the manual.

** Bookmarks

See the manual.


* Files
** Basic file handling

C-x C-f find-file
C-x C-r find-file-read-only
C-x C-v find-alternate-file
C-x 4 f find-file-other-window
C-x 5 f find-file-other-frame

C-x C-s save-buffer
C-x C-w write-file

M-x revert-buffer
M-x auto-revert-mode

M-x recover-file
M-x recover-session

** Diff and merging

M-x diff
M-x ediff
M-x diff-backup
M-x diff-buffer-with-file
M-x diff-buffers

M-x smerge-mode


* Inside minibuffer
** General

M-p previous-history-element
M-n next-history-element

** Ivy

M-r ivy-toggle-regexp-quote


* Miscellaneous 

** Word count

M-= count-words-region
M-x count-words


* TODO

A better way to scroll/find/go to a location outside the
window. Scrolling is only useful when I want to skim/scan a file top
to bottom, otherwise it is very distracting and tiring.

Push and pop location in a unified way. Return from xref definition,
return from previous mark, etc.

Better navigation between help buffers, forward and backward. It's not
desired that a second help buffer opens in the other window.

Goto help at point, like 'M-.'. And return, like 'M-,'. Bind
helpful-at-point.

Check help-* and helpful-* functions. help and helpful mode commands
in manual.

Run C-h m in Help and Helpful mode and check mode specific key
bindings.

Separate "selection" and "adding a location to mark ring". I don't
want the mark to be saved every time text is selected.

Stop Ivy matching when necessary. For example, there is an existing
file design-top.v, typing C-x C-f top.v ENTER opens design-top.v
rather than creating top.v.

Save as another file with single command.

Change tiling of windows from vertical to horizontal and vice versa.

Swiper commands. swiper-thing-at-point

Avy.

highlight-regexp and unhighlight-regexp

Emacs pull request scroll-margin > 0 together with follow-mode.

Syntax of regular expressions.

C-s for all project (like grep -r)

Switch to *occur* buffer after creation.

Quitting temporary windows, such as help, with q.

write-file replaces the buffer with the buffer that visits the new
file. Keep both buffers.

ediff control panel opens as a new frame, rather than a secondary echo
area/minibuffer.

Make read-only buffer writable and vice versa.

Easier way to cancel completion when tying. For example, I want to
type "buffer" and press ENTER, the completion suggests "buffers". The
ENTER selects the undesired suggestion rather than opening a new
line. One option is to hit SPACE and then ENTER, which leaves a
training space to the previous line.
