#+TITLE: Emacs Cheat Sheet
#+AUTHOR: Can Aknesil
#+STARTUP: content
#+OPTIONS: toc:nil

Keep it simple and to the basics unless it's necessary.

Made according to Emacs manual version 29.1.

* When in trouble
** Help and documentation lookup

C-h k describe-key
C-h c describe-key-briefly
C-h f describe-function
C-h v describe-variable
C-h o describe-symbol
C-h P describe-package
C-h m describe-mode

M-x eldoc-doc-buffer

C-h S info-lookup-symbol
M-x info-lookup-file

** Undo

C-/
C-x u
C-_   undo

C-? undo-redo

** Canceling

C-g
ESC ESC ESC keyboard-quit


* Navigation
** Basic motion

C-f forward-char
C-b backward-char
C-n next-line
C-p previous-line

C-a move-beginning-of-line
C-e move-end-of-line

M-f forward-word
M-b backward-word

M-a backward-sentence
M-e forward-sentence

M-} forward-paragraph
M-{ backword-paragraph

C-M-a beginning-of-defun
C-M-e end-of-defun

C-M-f forward-sexp
C-M-b backward-sexp
C-M-n forward-list
C-M-p backward-list
C-M-u backward-up-list
C-M-d down-list

M-< beginning-of-buffer
M-> end-of-buffer

** Basic scrolling

C-v scroll-up-command
M-v scroll-down-command

C-M-v scroll-other-window
C-M-SHIFT-v scroll-other-window-down
C-M-SHIFT-l recenter-other-window

C-l recenter-top-bottom
C-M-l reposition-window

** Search

C-s isearch-forward
C-r isearch-backward
C-s C-s (repeat previous search)
C-r C-r (repeat previous search)

M-s w isearch-forward-word
M-s _ isearch-forward-symbol
M-s . isearch-forward-symbol-at-point

C-M-s isearch-forward-regexp
C-M-r isearch-backward-regexp

M-r isearch-toggle-regexp (within isearch)

M-s o occur

M-g i imenu

** Grep

M-x grep
M-x find-grep

M-x lgrep
M-x rgrep
M-x zrgrep

M-x kill-grep

For grep buffer commands, see the manual.

** Ring navigation (go to and back)

C-SPC C-SPC (push to mark ring)
C-u C-SPC (return to last mark)
C-x C-SPC pop-global-mark

M-g M-g goto-line

C-x 4 . xref-find-definitions-other-window
C-x 5 . xref-find-definitions-other-frame

** Semantic mode

See the manual.

** Files

C-x C-f find-file
C-x C-r find-file-read-only
C-x C-v find-alternate-file
C-x 4 f find-file-other-window
C-x 4 r find-file-read-only-other-window
C-x 5 f find-file-other-frame
C-x 5 r find-file-read-only-other-frame

C-x C-s save-buffer
C-x C-w write-file

C-x i insert-file
M-x write-region

M-x revert-buffer
M-x auto-revert-mode

M-x recover-file
M-x recover-session

** Buffers

C-x b switch-to-buffer
C-x 4 b switch-to-buffer-other-window
C-x 5 b switch-to-buffer-other-frame
C-x LEFT previous-buffer
C-x RIGHT next-buffer

C-x C-b list-buffers
C-u C-x C-b (list only file visiting buffers)

C-x C-q read-only-mode

C-x k kill-buffer
M-x kill-some-buffers

** Windows

C-x 0 delete-window
C-x 1 delete-other-window
C-x 2 split-window-below
C-x 3 split-window-right
C-x 4 0 kill-buffer-and-window

C-x o other-window

C-x 4 4 other-window-prefix
C-x 4 1 same-window-prefix

SHIFT-LEFT windmove-left
SHIFT-RIGHT windmove-right
SHIFT-UP windmove-up
SHIFT-DOWN windmove-down

C-x SHIFT-LEFT windmove-delete-left
C-x SHIFT-RIGHT windmove-delete-right
C-x SHIFT-UP windmove-delete-up
C-x SHIFT-DOWN windmove-delete-down

C-c LEFT winner-undo
C-c RIGHT winner-redo

** Frames

C-x 5 2 make-frame-command
C-x 5 c clone-frame

C-x 5 0 delete-frame
C-z suspend-frame

C-x 5 o other-frame
C-x 5 1 delete-other-frames

C-x 5 5 other-frame-prefix

M-F10 toggle-frame-maximized
F11 toggle-frame-fullscreen

** Tab lines

See the manual.

** Tab bars

See the manual.

** Indirect buffers

See the manual.

** Follow mode

M-x follow-mode

** Line truncation and visual line mode

C-x x t toggle-truncate-lines
M-x visual-line-mode

** Narrowing

See the manual.

** View Mode

See the manual.

** Speedbar

See the manual.


* Basic editing
** Deletion, killing, and yanking

BACKSPACE delete-backward-char
C-d delete-char

C-k kill-line
C-SHIFT-BACKSPACE kill-whole-line

M-BACKSPACE backward-kill-word
M-d kill-word

C-M-k kill-sexp

C-w kill-region
M-w kill-ring-save

C-y yank
M-y yank-pop
C-u C-y (yank and leave point at the beginning)
C-u M-y (yank-pop and leave point at the beginning)

** Region (selection)

C-SPC set-mark-command
C-x C-x exchange-mark-and-point

M-h mark-paragraph
C-M-h mark-defun
C-x h mark-whole-buffer


* Smart editing
** Blank lines and whitespace

C-o open-line
C-M-o split-line

M-\ delete-horizontal-space
M-SPC just-one-space
C-x C-o delete-blank-lines
M-^ delete-indentation
M-x delete-trailing-whitespace

** Indentation

TAB indent-for-tab-command
M-m back-to-indentation
C-q TAB (insert TAB character)

C-M-\ indent-region
C-M-q prog-indent-sexp

M-x indent-relative
M-^ delete-indentation

** Replacement

M-x replace-string
M-% query-replace

M-x replace-regexp
C-M-% query-replace-regexp

** Smart insertion

C-x r N rectangle-number-lines
C-u C-x r N (rectangle-number-lines custom initial number and format string)

** Repetition, and keyboard macro

C-u <n>... <command>
C-x z [z...] repeat

C-x ( kmacro-start-macro
C-x ) kmacro-end-macro
C-x e [e...] kmacro-end-and-call-macro

** Rectangles

C-x r t string-rectangle

C-x r k kill-rectangle
C-x r c clear-rectangle

C-x r M-w copy-rectangle-as-kill
C-x r y yank-rectangle

** Correcting spelling

M-$ ispell-word
M-x ispell
M-x ispell-comments-and-strings

** Filling text

M-q fill-paragraph
M-x fill-region
M-x fill-region-as-paragraph

C-x . set-fill-prefix

M-x center-line
M-x center-region
M-x center-paragraph

** Comments

M-; comment-dwin
C-x C-; comment-line
C-u M-; comment-kill

M-x comment-region
M-x uncomment-region

M-j indent-new-comment-line

** Completion

C-M-i completion-at-point

** Overwrite mode (Insert)

M-x overwrite-mode
M-x binary-overwrite-mode

** Case conversion

M-l downcase-word
M-u upcase-word
M-c capitalize-word

C-x C-l downcase-region
C-x C-u upcase-region
M-x capitalize-region

** Parentheses

M-x check-parens

** Hideshow

See the manual.

** Highlighting

See the manual.

** Accumulating text

See the manual.

** Transposing text

See the manual.

** Registers

See the manual.

** Bookmarks

See the manual.

** Pages

See the manual.

** Enriched text

See the manual.

** Text-based tables

See the manual.

** Two-column editing

See the manual.


* Files
** Diff and merging

M-x diff
M-x ediff
M-x diff-backup
M-x diff-buffer-with-file
M-x diff-buffers

C-x v = vc-diff
C-x v D vc-root-diff

M-x smerge-mode

** File name cache

See the manual.


* Inside minibuffer
** General

M-p previous-history-element
M-n next-history-element

** Ivy

M-r ivy-toggle-regexp-quote


* Interractive programming
** Compilation

M-x compile
M-x recompile
M-x kill-compilation

For compilation mode commands, see the manual.

** Lisp execution

M-x load-file
M-x load-library

M-: eval-expression
C-x C-e eval-last-sexp
C-M-x eval-defun
M-x eval-region
M-x eval-buffer

M-x lisp-interaction-mode
M-x scratch-buffer
C-j eval-print-last-sexp

M-x ielm

M-x run-lisp
M-x run-scheme

** Flymake

See the manual.

** Running debuggers

See the manual.

* Version control
** VC

See the manual.


* Miscellaneous 

** Word count

M-= count-words-region
M-x count-words


* TODO

A better way to scroll/find/go to a location outside the
window. Scrolling is only useful when I want to skim/scan a file top
to bottom, otherwise it is very distracting and tiring.

Push and pop location in a unified way. Return from xref definition,
return from previous mark, etc.

Better navigation between helpful buffers, forward and backward. It's
not desired that a second help buffer opens in the other window. Help
buffers don't have this problem.

Goto help at point, like 'M-.'. And return, like 'M-,'.

Run C-h m in Help/Helpful buffer and check mode specific key bindings.

Separate "selection" and "adding a location to mark ring". I don't
want the mark to be saved every time text is selected.

Stop Ivy matching when necessary. For example, there is an existing
file design-top.v, typing C-x C-f top.v ENTER opens design-top.v
rather than creating top.v.

Save as another file with single command.

write-file replaces the buffer with the buffer that visits the new
file. Keep both buffers.

Change tiling of windows from vertical to horizontal and vice versa.

Swiper commands. swiper-thing-at-point

Isearch forward and backward together.

Avy.

highlight-regexp and unhighlight-regexp

Emacs pull request scroll-margin > 0 together with follow-mode.

Syntax of regular expressions.

C-s for all project (like grep -r)

Many commands opens a buffer in other window but not move to it, such
as list-buffers. Moving to the newly opened buffer is often the
desired behavior.

Switch to *occur* buffer after creation.

Documentation page Choosing a "Window for Displaying a Buffer":
https://www.gnu.org/software/emacs/manual/html_node/elisp/Choosing-Window.html

Quitting temporary windows, such as help, with q.

ediff control panel opens as a new frame, rather than a secondary echo
area/minibuffer.

Easier way to cancel completion when tying. For example, I want to
type "buffer" and press ENTER, the completion suggests "buffers". The
ENTER selects the undesired suggestion rather than opening a new
line. One option is to hit SPACE and then ENTER, which leaves a
training space to the previous line. Solution: Insert new line with
C-j.

Alternatively, only use M-p, M-n, M-ENTER to navigate and select in
completion list, as with the default completion built-in Emacs. This
will also enable moving cursor up and down when the completion list is
open.

Sometimes when the point is at the end of a line, the line shifts
right by one column (line number included). Prevent it. In org-mode.

goto-line in another buffer.

Set Emacs C source directory.

undelete-frame-mode (version 29 or higher) to undelete recently
deleted frames with C-x 5 u.

Desktop library to save and restore sessions.

Some messages in echo area disappears after some seconds. Disable this
(or extend the duration) so that I can take as much time as possible
when reading it.

Configure/learn tab bars (similar to i3 workspaces) not to use the bar
but be accessible via commands.

Non-agressive parenthesis insertion. For example, I don't want the
closing paranthesis to be inserted after I type the openning
paranthesis; but I want emacs to put closing paranthesis to the third
line, put the point to the second line and indent.

Text alighment left (default with M-q), center, and right. Solution
for center: M-x center-{line,region,paragraph}.

Company vs builting completion.

Outline mode vs org mode.

Org mode manual.

Tex mode vs auctex.

Make M-; insert the comment after a single space, rather than a
TAB-like distance.

Which-key mode doesn't work with Ivy. Builtin feature for which-key?

Disable electric layout mode for any buffer. Some modes, such as C and
Verilog, enables this by default, which is very annoying.

Hideshow mode vs selective display vs outline mode vs foldout package.

Built-in version control (VC) vs projectile.

Built-in project commands vs projectile.

diff-hl mode to highlight uncommited changes in the margin. Is there a
built-in method?

Treemacs vs built-in speedbar.

