# i3 config file (v4)

set $LINUX_CONFIGURATION_DIR ~/Programs/linux-configuration

set $FONT pango:DejaVu Sans Mono 10

set $TERMINAL i3-sensible-terminal
# set $TERMINAL xfce4-terminal

# set $DROP_DOWN_TERMINAL xfce4-terminal --drop-down
set $DROP_DOWN_TERMINAL true

# Some wallpaper commands
# feh --bg-max <path>
# nitrogen --restore

# set $DISPLAY_AND_WALLPAPER_CONFIG_COMMAND nitrogen --restore
# set $DISPLAY_AND_WALLPAPER_CONFIG_COMMAND /bin/sh -c 'autorandr --change; sleep 0.5; nitrogen --restore'
# Note that wallpaper configuration can also be hooked to autorandr
set $DISPLAY_AND_WALLPAPER_CONFIG_COMMAND true

# set $LOCK_COMMAND i3lock
# set $LOCK_COMMAND xfce4-screensaver-command --lock

# The --image spans through multiple monitors. --tiling enables repeating the image in the second screen.
# Image must be an absolute path to a .png file
# set $LOCK_COMMAND i3lock --image=$i3lock_wallpaper_file --tiling
set $LOCK_COMMAND true

# set $LOCK_BEFORE_SUSPEND_SETUP_COMMAND xss-lock --transfer-sleep-lock -- i3lock --nofork
set $LOCK_BEFORE_SUSPEND_SETUP_COMMAND true

# set $COMPOSITOR picom
set $COMPOSITOR true

# Disable locking related xorg settings that may interfere with xfce4-screensaver and xfce4-powermanager
# set $SCREENSAVER_SETUP_COMMAND /bin/sh -c 'xset s off; xset -dpms; xfce4-screensaver'
set $SCREENSAVER_SETUP_COMMAND true

# set $NETWORK_MANAGER_APPLET nm-applet
set $NETWORK_MANAGER_APPLET true

# set $BLUETOOTH_APPLET blueman-applet
set $BLUETOOTH_APPLET true

# set $AUDIO_APPLET pasystray # runs automatically
# set $AUDIO_APPLET xfce4-volumed-pulse
set $AUDIO_APPLET true

# set $POWER_MANAGER xfce4-power-manager
set $POWER_MANAGER true

# set $IBUS_DAEMON ibus-daemon -rxRd
set $IBUS_DAEMON true

set $ADDITIONAL_STARTUP_COMMANDS true

# System specific configuration above and below the include statement
include $LINUX_CONFIGURATION_DIR/i3.conf
