# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
  colors = true
  interval = 5
}

order += "wireless _first_"
#order += "ethernet _first_"
#order += "ethernet enxd0c1b51f247f"
#order += "ethernet enp0s31f6"
order += "disk /"
order += "memory"
order += "cpu_usage"
order += "cpu_temperature 0"
order += "read_file keyboard_layout"
order += "tztime local"
order += "volume master"
#order += "battery all"

wireless _first_ {
  #format_up = "W: (%quality at %essid) %ip"
  format_up = "W %essid %bitrate %ip"
  format_down = "W down"
  format_quality = "%d%s"
  format_bitrate = "%g%cb/s"
  format_signal = "%d%s"
  format_noise = "%d%s"
}

ethernet _first_ {
  format_up = "E %ip"
  format_down = "E down"
}

ethernet enxd0c1b51f247f {
  format_up = "E %ip"
  format_down = "E down"
}

ethernet enp0s31f6 {
  format_up = "E %ip"
  format_down = "E down"
}

disk "/" {
  format = "/ %avail"
}

memory {
  #format = "%used | %available"
  format = "RAM %used"
  threshold_critical = "1G"
  unit = "Gi"
}

cpu_usage {
  format = "CPU %usage"
  max_threshold = 85
}

cpu_temperature 0 {
  format = "%degrees°C"
  max_threshold = 85
  path = "/sys/class/hwmon/hwmon2/temp1_input" # AMD, hwmon2 is k10temp, temp1_label is Tctl
}

tztime local {
  format = "%Y-%m-%d %H:%M"
}

read_file keyboard_layout {
  path = "/tmp/keyboard_layout_for_i3status"
  format = "%content"
}

volume master {
  format = "♪ %volume"
  format_muted = "♪ %volume (muted)"
  device = "default"
  mixer = "Master"
  mixer_idx = 0
}

battery all {
  format = "%status %percentage %remaining"
}